@host = http://localhost:5011

### Create Conversation
POST {{host}}/conversations
Content-Type: application/json

### Send Message
POST {{host}}/messages
Content-Type: application/json

{
  "conversationId": "ca28b5134d124278b7a0a47d3604a256",
  "message": "Explain how Azure Functions TimerTrigger works and provide a short C# example. Is is required to consume this info using the MCP. If no awnser is received, respond 'I could not find the answer to your question.'"
}
